# pasta.yaml
# zips chrome extension `src/` folder into `pasta.zip`

name: pasta-zip

on:
  push:
    paths:
      - 'src/**'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - name: checkout
          uses: actions/checkout@v3
          
        - name: convert pdfs to png images
          run: |
            tree
            
            rm -rf dist
            mkdir -p dist
            
            tree

            zip pasta.zip -r src -x *.git* -x .DS_Store > pasta.log
            cat pasta.log            

            mv pasta.zip dist
            
        - name: show a tree
          run: |
            pwd
            tree .
            
        - name: setup git config
          run: |
            pwd
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            
        - name: commitifnew
          run: |
            pwd
            git add .
            
            newstuff=$( git status | grep "Changes to be committed" | sed 's/ //g' )
            echo $newstuff
            
            echo ${#newstuff}
            
            if (( ${#newstuff} > 0 )); then
              git commit -m "generated by dofufa-pasta-zip workflow"
              git push origin main              
            fi
